### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kazutoichikawa** [kazutoichikawa/furima-32531#24]
挙動確認の方、よろしくお願い致します。

○フリマアプリのURL
https://furima-32531.herokuapp.com/

○Basic認証のIDとパスワード 
ID: admin
Password: 2222

○出品者用のメールアドレスとパスワード 
ID: sample@sample.jp
Password: sample11

○購入者用のメールアドレスとパスワード
ID: sample2@sample.jp
Password: sample22

○PAY.JPのテストカード情報
購入用カードの番号: 4242424242424242
期限: 3/33
セキュリティコード: 123

以上です。よろしくお願い致します。

**Comment by MasaakiTanabashi** [comment]
kazutoichikawaさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**◎エラーメッセージが表示されません。**
新規登録ページで適切では無い値が入力された場合、
（情報は受け入れられず）エラーメッセージを出力させるように修正しましょう。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kazutoichikawa** [comment]
挙動確認ありがとうございます。
ご指摘の点、修正致しましたので、確認をお願い致します。

**Comment by MasaakiTanabashi** [comment]
kazutoichikawaさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
